name: smoke_signal
description: "An Empathetech live activities social network designed to keep us off our screens."
version: 2.0.0+2
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter (Google)
  go_router: ^14.8.1
  http: ^1.5.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

  # Community
  email_validator: ^3.0.0
  feedback: ^3.2.0
  cached_network_image: ^3.4.1
  flutter_localized_locales: ^2.0.5
  flutter_platform_widgets: ^9.0.0
  provider: ^6.1.5

  empathetech_flutter_ui:
    path: ../empathetech_flutter_ui

dev_dependencies:
  dependency_validator: ^5.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/app-icon.png
    - assets/images/dark-forest.png
    - assets/images/light-forest.png
    - assets/images/smoke-signal.gif

flutter_launcher_icons:
  image_path: assets/images/app-icon.png
  adaptive_icon_foreground: assets/images/app-icon.png
  adaptive_icon_background: "#A520DA"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  image: assets/images/app-icon.png
  color: "#A520DA"
  android: true
  ios: true
  web: true
