// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_WL7t1NgCkMyB2cGC0pgcaD8KRYriH2c',
    appId: '1:765876318923:web:8c51de1dd885cbf672214e',
    messagingSenderId: '765876318923',
    projectId: 'smoke-signal-8e445',
    authDomain: 'smoke-signal-8e445.firebaseapp.com',
    storageBucket: 'smoke-signal-8e445.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXfV2M1d440kzC4PrgKCrgtl-4KDEUil0',
    appId: '1:765876318923:android:afc14681c5e51e1572214e',
    messagingSenderId: '765876318923',
    projectId: 'smoke-signal-8e445',
    storageBucket: 'smoke-signal-8e445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAhzeszbsg04m4dyibCxhszqI1y0BgaM',
    appId: '1:765876318923:ios:bd2ba79a6180ce0972214e',
    messagingSenderId: '765876318923',
    projectId: 'smoke-signal-8e445',
    storageBucket: 'smoke-signal-8e445.appspot.com',
    iosBundleId: 'net.empathetech.smokeSignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXAhzeszbsg04m4dyibCxhszqI1y0BgaM',
    appId: '1:765876318923:ios:bd2ba79a6180ce0972214e',
    messagingSenderId: '765876318923',
    projectId: 'smoke-signal-8e445',
    storageBucket: 'smoke-signal-8e445.appspot.com',
    iosBundleId: 'net.empathetech.smokeSignal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_WL7t1NgCkMyB2cGC0pgcaD8KRYriH2c',
    appId: '1:765876318923:web:02434485a2bf5cd072214e',
    messagingSenderId: '765876318923',
    projectId: 'smoke-signal-8e445',
    authDomain: 'smoke-signal-8e445.firebaseapp.com',
    storageBucket: 'smoke-signal-8e445.appspot.com',
  );
}
